version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/chross-chain-faucet
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_DATABASE: chross-chain-faucet
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: